### ISSUE TITLE
IO Error on python 2 when chart CSV includes UTF-8 character

### ISSUE THREAD

**Issue by reki2000** [m3dev/pptx-template#12]
on Python 2.7 environment, ``python setup.py test`` failed with:

```
======================================================================
ERROR: test_simple (test.cliTest.MyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\me\git\pptx-template\test\cliTest.py", line 12, in test_simple
    main()
  File "c:\me\git\pptx-template\pptx_template\cli.py", line 53, in main
    process_slide(ppt, slide, model)
  File "c:\me\git\pptx-template\pptx_template\cli.py", line 20, in process_slide
    edit_slide(slide, model)
  File "c:\me\git\pptx-template\pptx_template\core.py", line 40, in edit_slide
    ch.load_data_into_chart(chart, model)
  File "c:\me\git\pptx-template\pptx_template\chart.py", line 98, in load_data_into_chart
    replace_chart_data_with_csv(chart, chart_id, chart_setting)
  File "c:\me\git\pptx-template\pptx_template\chart.py", line 74, in replace_chart_data_with_csv
    chart_data = _build_chart_data(csv)
  File "c:\me\git\pptx-template\pptx_template\chart.py", line 36, in _build_chart_data
    log.debug(u"adding series %s" % (col.name))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)

----------------------------------------------------------------------
```

**Comment by reki2000** [comment]
already fixed. closed.
